# build.yml 最终版
name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true

    - name: Build Android binaries
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-binaries
        path: |
          build/android-binaries.tar.gz
          build/android/**/*
        retention-days: 7
