name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Cache Cloudflare Go
        id: cache-go
        uses: actions/cache@v4
        with:
          path: |
            go/bin
            go/pkg
          key: ${{ runner.os }}-cloudflare-go-${{ env.CF_GO_VERSION }}
          restore-keys: |
            ${{ runner.os }}-cloudflare-go-

      - name: Clone and Build Cloudflare Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/cloudflare/go
          cd go
          echo "CF_GO_VERSION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          cd src
          ./make.bash
          cd $GITHUB_WORKSPACE

      - name: Setup Cloudflare Go Path
        run: |
          echo "$GITHUB_WORKSPACE/go/bin" >> $GITHUB_PATH
          echo "GOROOT=$GITHUB_WORKSPACE/go" >> $GITHUB_ENV
          $GITHUB_WORKSPACE/go/bin/go version

      - name: Build with build.sh
        env:
          GOROOT: ${{ env.GOROOT }}
          PATH: ${{ env.GOROOT }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${{ env.PATH }}
        run: |
          echo "GOROOT: ${{ env.GOROOT }}"
          echo "PATH: ${{ env.PATH }}"
          echo "go version: $(go version)"
          ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/*.*
          retention-days: 1