name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cloudflare Go
        id: cache-go
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/go
          key: ${{ runner.os }}-cf-go-${{ env.CF_GO_VERSION }}
          restore-keys: |
            ${{ runner.os }}-cf-go

      - name: Set up Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build and Install Cloudflare Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/cloudflare/go
          cd go
          echo "CF_GO_VERSION=$(git rev-parse HEAD)" >> $GITHUB_ENV
          cd src
          ./make.bash

      - name: Build with build.sh
        env:
          GOBIN: ${{ github.workspace }}/go/bin
          GOROOT: ${{ github.workspace }}/go
        run: |
          echo "go version: $(go version)"
          ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/*.*
          retention-days: 1